### ISSUE TITLE
Checklist for v0.2 release

### ISSUE THREAD

**Issue by sgreenbury** [Urban-Analytics-Technology-Platform/popgetter-cli#58]
- [x] Check the seven manually derived metrics are searchable for each country
- [x] Check docs
- [x] Merge #56, #57; aim to implement #55 
- [x] Confirm the functionality for each part of the CLI's API. For any parts not yet implemented, add the following for example:
  ```rust
  todo!("The option to filter by `some unimplemented property` is not implemented for the current release")
  ```

**Comment by sgreenbury** [comment]
Notes on trying the CLI with @andrewphilipsmith:
- [ ] Set countries as unimplemented (or impl)
- [ ] Set surveys as unimplemented
- [ ] Country search over all country metadata would be useful
- [ ] Geometry levels for each country
- [ ] Add option `--no-geometry` to exclude downloading
